name: Cattle_hmx
description: Default Cattle template HMX
stacks:
  - name: network-services
    templateId: 'hmx_catalog:infra*network-services'
  - name: ipsec
    templateId: 'library:infra*ipsec'
  - name: scheduler
    templateId: 'library:infra*scheduler'
  - name: healthcheck
    templateId: 'library:infra*healthcheck'
